"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";

export function DriverAcceptInviteClient({ token }: { token: string }) {
  const router = useRouter();
  const [valid, setValid] = useState<null | boolean>(null);
  const [invite, setInvite] = useState<{
    driverName: string | null;
    driverEmail: string;
    carrierName: string;
    inviterName: string;
  } | null>(null);
  const [fullName, setFullName] = useState("");
  const [phone, setPhone] = useState("");
  const [cdlNumber, setCdlNumber] = useState("");
  const [cdlState, setCdlState] = useState("");
  const [cdlExpiry, setCdlExpiry] = useState("");
  const [password, setPassword] = useState("");
  const [confirm, setConfirm] = useState("");
  const [err, setErr] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);

  useEffect(() => {
    if (!token) {
      setValid(false);
      return;
    }
    void (async () => {
      const res = await fetch(`/api/freight/validate-invite-token?token=${encodeURIComponent(token)}`);
      const data = await res.json();
      if (!data.valid) {
        setValid(false);
      } else {
        setValid(true);
        setInvite({
          driverName: data.driverName,
          driverEmail: data.driverEmail,
          carrierName: data.carrierName,
          inviterName: data.inviterName,
        });
        setFullName(data.driverName ?? "");
      }
    })();
  }, [token]);

  async function submit(e: React.FormEvent) {
    e.preventDefault();
    if (password !== confirm || password.length < 8) {
      setErr("Password mismatch or too short.");
      return;
    }
    setBusy(true);
    setErr(null);
    try {
      const res = await fetch("/api/freight/accept-driver-invite", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          token,
          fullName,
          phone,
          cdlNumber,
          cdlState,
          cdlExpiry,
          password,
        }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || "Signup failed");
      const sb = createClient();
      if (invite?.driverEmail) {
        await sb?.auth.signInWithPassword({
          email: invite.driverEmail,
          password,
        });
      }
      router.replace("/freight/driver/dashboard");
      router.refresh();
    } catch (ex: unknown) {
      setErr(ex instanceof Error ? ex.message : "Error");
    } finally {
      setBusy(false);
    }
  }

  if (valid === false) {
    return (
      <div className="rounded-3xl border border-red-400/35 bg-[#2a0710]/40 px-8 py-10 text-center">
        <p className="text-[var(--color-text)] font-semibold">Invalid invite</p>
        <p className="mt-3 text-xs text-[var(--color-muted)]">
          Expired invites must be regenerated by your dispatcher or verified carrier tenant.
        </p>
        <Link href="/freight/login" className="mt-6 inline-flex text-[var(--color-accent)] underline">
          Freight login portal
        </Link>
      </div>
    );
  }

  if (valid !== true || !invite) {
    return <p className="text-center text-sm text-[var(--color-muted)]">Validating invitation…</p>;
  }

  return (
    <div className="rounded-3xl border border-[var(--color-border)] bg-[var(--color-surface)]/40 px-8 py-10">
      <h1 className="text-2xl font-bold text-[var(--color-text)]" style={{ fontFamily: "var(--font-display)" }}>
        Welcome to Alpha Freight
      </h1>
      <p className="mt-3 text-sm text-[var(--color-muted)]">
        {invite.inviterName} invited you to join <strong className="text-[var(--color-text)]">{invite.carrierName}</strong>.
      </p>
      <form onSubmit={submit} className="mt-10 space-y-4 max-w-lg">
        {err ? <p className="text-sm text-red-200">{err}</p> : null}
        <label className="text-xs text-[var(--color-muted)]">Full legal name</label>
        <input required className="w-full rounded-lg border border-[var(--color-border)] bg-[#050912] px-3 py-2" value={fullName} onChange={(e) => setFullName(e.target.value)} />
        <label className="text-xs text-[var(--color-muted)]">Email (readonly)</label>
        <input readOnly value={invite.driverEmail} className="w-full cursor-not-allowed rounded-lg border border-[var(--color-border)] bg-[#0b1120] px-3 py-2 opacity-70" />
        <label className="text-xs text-[var(--color-muted)]">Phone</label>
        <input required className="w-full rounded-lg border border-[var(--color-border)] bg-[#050912] px-3 py-2" value={phone} onChange={(e) => setPhone(e.target.value)} />
        <div className="grid gap-4 sm:grid-cols-2">
          <div>
            <label className="text-xs text-[var(--color-muted)]">CDL number</label>
            <input required className="mt-1 w-full rounded-lg border border-[var(--color-border)] bg-[#050912] px-3 py-2" value={cdlNumber} onChange={(e) => setCdlNumber(e.target.value)} />
          </div>
          <div>
            <label className="text-xs text-[var(--color-muted)]">State (two letters)</label>
            <input required maxLength={2} className="mt-1 w-full rounded-lg border border-[var(--color-border)] bg-[#050912] px-3 py-2 uppercase" value={cdlState} onChange={(e) => setCdlState(e.target.value)} />
          </div>
        </div>
        <label className="text-xs text-[var(--color-muted)]">CDL expiry</label>
        <input required type="date" className="w-full rounded-lg border border-[var(--color-border)] bg-[#050912] px-3 py-2" value={cdlExpiry} onChange={(e) => setCdlExpiry(e.target.value)} />
        <label className="text-xs text-[var(--color-muted)]">Password</label>
        <input required type="password" className="w-full rounded-lg border border-[var(--color-border)] bg-[#050912] px-3 py-2" value={password} onChange={(e) => setPassword(e.target.value)} />
        <label className="text-xs text-[var(--color-muted)]">Confirm password</label>
        <input required type="password" className="w-full rounded-lg border border-[var(--color-border)] bg-[#050912] px-3 py-2" value={confirm} onChange={(e) => setConfirm(e.target.value)} />
        <button disabled={busy} className="w-full rounded-lg bg-[var(--color-accent)] py-3 text-sm font-bold text-[#05080f] disabled:opacity-40">
          {busy ? "Creating…" : "Create my driver account"}
        </button>
      </form>
    </div>
  );
}
