import type { CarrierDashboardData } from "./carrier-dashboard-types";

export function getCarrierMockDashboard(companyName = "ABC Trucking LLC"): CarrierDashboardData {
  return {
    carrier: {
      carrier_id: "C001",
      company_name: companyName,
      mc_number: "123456",
      dot_number: "789123",
      owner: "John Smith",
      status: "Active",
    },
    summary: {
      weekly_revenue: 12450,
      monthly_revenue: 48200,
      active_loads: 4,
      rpm: 2.78,
      miles_driven: 3450,
      outstanding_invoices: 3200,
    },
    current_load: {
      load_number: "LD-2045",
      pickup: "Dallas, TX",
      delivery: "Atlanta, GA",
      rate: 2450,
      status: "In Transit",
      eta: "4:30 PM",
      truck_location: "Memphis, TN",
    },
    trucks: [
      {
        truck_id: "TRK001",
        truck_number: "101",
        driver: "Mike Johnson",
        equipment: "Dry Van",
        location: "Memphis, TN",
        status: "Loaded",
        lat: 35.1495,
        lng: -90.049,
      },
      {
        truck_id: "TRK002",
        truck_number: "102",
        driver: "Carlos Rivera",
        equipment: "Reefer",
        location: "Houston, TX",
        status: "Available",
        lat: 29.7604,
        lng: -95.3698,
      },
    ],
    drivers: [
      { driver_id: "DRV001", name: "Mike Johnson", phone: "+1 (555) 555-0101", status: "Driving", score: 94 },
      { driver_id: "DRV002", name: "Carlos Rivera", phone: "+1 (555) 555-0102", status: "Available", score: 88 },
      { driver_id: "DRV003", name: "James Lee", phone: "+1 (555) 555-0103", status: "Off Duty", score: 91 },
    ],
    loads: [
      {
        load_id: "LD-2045",
        load_number: "LD-2045",
        pickup: "Dallas, TX",
        delivery: "Atlanta, GA",
        rate: 2450,
        status: "In Transit",
        dispatcher: "Sarah Wilson",
        miles: 781,
      },
      {
        load_id: "LD-2046",
        load_number: "LD-2046",
        pickup: "Chicago, IL",
        delivery: "Detroit, MI",
        rate: 980,
        status: "Assigned",
        dispatcher: "Sarah Wilson",
        miles: 283,
      },
      {
        load_id: "LD-2047",
        load_number: "LD-2047",
        pickup: "Phoenix, AZ",
        delivery: "Los Angeles, CA",
        rate: 1120,
        status: "Booked",
        dispatcher: "Muhammad Mikran",
        miles: 372,
      },
      {
        load_id: "LD-2048",
        load_number: "LD-2048",
        pickup: "Denver, CO",
        delivery: "Salt Lake City, UT",
        rate: 890,
        status: "Available",
        dispatcher: "Sarah Wilson",
        miles: 525,
      },
    ],
    payments: {
      paid_this_month: 8750,
      unpaid_invoices: 3200,
      factoring_status: "Approved",
      total_earnings_ytd: 284600,
    },
    documents: [
      { document_type: "Insurance", expiration_date: "2026-12-15", status: "Valid" },
      { document_type: "MC Authority", expiration_date: "2027-01-01", status: "Valid" },
      { document_type: "BOL Template", expiration_date: "—", status: "On File" },
      { document_type: "W-9", expiration_date: "—", status: "On File" },
    ],
    compliance: {
      insurance_status: "Active",
      insurance_expiry: "2026-12-15",
      mc_authority: "Active",
      mc_expiry: "2027-01-01",
      cdl_expiry: "2028-06-30",
      ifta_due: "2026-07-31",
      registration_expiry: "2027-03-15",
    },
    dispatcher: {
      name: "Sarah Wilson",
      email: "dispatch@alphafreightnetwork.com",
      phone: "+1 (555) 111-2222",
    },
    revenue_weekly: [
      { label: "Mon", amount: 2100 },
      { label: "Tue", amount: 1850 },
      { label: "Wed", amount: 2400 },
      { label: "Thu", amount: 2200 },
      { label: "Fri", amount: 1950 },
      { label: "Sat", amount: 1200 },
      { label: "Sun", amount: 750 },
    ],
    revenue_monthly: [
      { label: "Jan", amount: 38200 },
      { label: "Feb", amount: 41100 },
      { label: "Mar", amount: 44800 },
      { label: "Apr", amount: 46200 },
      { label: "May", amount: 48200 },
      { label: "Jun", amount: 52100 },
    ],
    rpm_trend: [
      { label: "W1", amount: 2.62 },
      { label: "W2", amount: 2.71 },
      { label: "W3", amount: 2.68 },
      { label: "W4", amount: 2.78 },
    ],
    fuel_expense_month: 4280,
    maintenance_alerts: 1,
    ai_load_recommendations: [
      {
        load_id: "AI-901",
        load_number: "REC-901",
        pickup: "Nashville, TN",
        delivery: "Charlotte, NC",
        rate: 1340,
        status: "Recommended",
        dispatcher: "Sarah Wilson",
        miles: 410,
      },
    ],
    data_source: "mock",
  };
}
